IO.inspect("Hello world")
IO.inspect("Hello world from Elixir")
IO.inspect(1)
IO.inspect(0x1F)
IO.inspect(1.0)
IO.inspect(true)
IO.inspect(:atom)
IO.inspect([1, 2, 3])
IO.inspect({1, 2, 3})
IO.inspect(1 + 2)
IO.inspect(8 * 8)
IO.inspect(10 / 2)
IO.inspect(div(10, 2))
IO.inspect(div(10, 3))
IO.inspect(10 / 3)
IO.inspect(round(3.58))
IO.inspect(is_atom(false))
IO.inspect(is_boolean(false))
IO.inspect(is_binary("hello"))
IO.inspect(byte_size("hello"))
